name: Bump Version (dev)

on:
  pull_request:
    types:
      - closed
    branches:
      - dev

jobs:
  bump-version:
    if: github.event.pull_request.merged == true

    name: Bump version
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up uv
        id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.10"
          cache-dependency-glob: "**/pyproject.toml"

      - name: Install build dependencies
        run: |
          uv sync --extra build

      - name: Bump version (dev)
        run: |
          uv run hatch version dev

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Bump version number (dev segment)
          commit_author: GitHub Actions <actions@github.com>
