name: Bump Version (dev)

on:
  push:
    branches:
      - dev

jobs:
  build:
    if: (! contains(github.event.head_commit.message, '[no bump]'))

    name: Bump version
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set env variables
      run: |
        echo "${{ github.event.head_commit.message }}"

    - name: Install dependencies
      run: |
        pip install -e .[build]

    - name: Bump version (dev)
      run: |
        hatch version dev

    - name: Commit files
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Bump version number (dev segment)
        commit_author: GitHub Actions <actions@github.com>
