name: Test Duration Logger

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      max-parallel: 1
      matrix:
        python-version: ['3.12']
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            uv sync --extra test --extra extras            

      - name: Run tests
        run: |
          rm test/fixtures/.test_durations*
          uv run pytest \
            --nbval-lax examples/ \
            --store-durations \
            --durations-path test/fixtures/.test_durations_examples
          uv run pytest test/ \
            --store-durations \
            --durations-path test/fixtures/.test_durations_unit

      - name: Commit and push test duration files
        uses: EndBug/add-and-commit@v9
        with:
          add: 'test/fixtures'
          author_name: github-actions
          author_email: actions@github.com
          message: 'test: Update test duration log.'
